# Generated by Django 5.1.7 on 2025-03-25 05:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Question Body')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='Correct Answer')),
                ('options', models.JSONField(verbose_name='Options')),
                ('type', models.CharField(default='Multiple Choice', max_length=50, verbose_name='Type')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subjects', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('essay', 'Essay'), ('mixed', 'Mixed')], default='mcq', max_length=20, verbose_name='Exam Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('finished', 'Finished')], max_length=10, verbose_name='Status')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('end_time', models.DateTimeField(verbose_name='End time')),
                ('max_score', models.PositiveIntegerField(verbose_name='Max score')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('questions', models.ManyToManyField(blank=True, to='exam.question', verbose_name='Questions')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subjects', verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_time', 'status'], name='exam_exam_start_t_80161e_idx'),
        ),
    ]
