# Generated by Django 5.1.7 on 2025-03-25 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='examgroup',
            name='exams',
            field=models.ManyToManyField(to='exam.exam', verbose_name='Exams'),
        ),
        migrations.AddField(
            model_name='examgroup',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Students'),
        ),
        migrations.AddField(
            model_name='examstatistics',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='Exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, to='exam.question', verbose_name='Questions'),
        ),
        migrations.AddField(
            model_name='questionscore',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='Exam'),
        ),
        migrations.AddField(
            model_name='questionscore',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question', verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subjects', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subjects', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='submission',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Evaluated by'),
        ),
        migrations.AddField(
            model_name='submission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam', verbose_name='Exam'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterUniqueTogether(
            name='questionscore',
            unique_together={('question', 'exam')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['start_time', 'status'], name='exam_exam_start_t_80161e_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'submitted_at'], name='exam_submis_student_103fd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('exam', 'student', 'attempt_number')},
        ),
    ]
