# Generated by Django 5.1.7 on 2025-03-26 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_questionoption_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='answers',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Answer Text')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='answers/%Y/%m/%d/', verbose_name='Answer File')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.question', verbose_name='Question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', related_query_name='answers', to='exam.submission', verbose_name='Submission')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
