# Generated by Django 5.1.7 on 2025-03-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_submission_answers_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_proctored',
            field=models.BooleanField(default=False, verbose_name='Is Proctored'),
        ),
    ]
