# Generated by Django 5.1.7 on 2025-04-21 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_exam_is_proctored'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'ExamCategory',
                'verbose_name_plural': 'ExamCategories',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='proctoring_url',
            field=models.URLField(blank=True, null=True, verbose_name='Proctoring havolasi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.examcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='NationalStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='DTS kodi')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.subjects', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'NationalStandart',
                'verbose_name_plural': 'NationalStandarts',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='standard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.nationalstandard', verbose_name='DTS'),
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=100, verbose_name='Hodisa')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
