# Generated by Django 5.1.7 on 2025-03-26 05:14

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('news', 'News'), ('exam', 'Exam'), ('announcement', 'Announcement'), ('submission', 'Submission'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('group', 'Group Only'), ('private', 'Private')], default='public', max_length=20)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('content_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[500, 350], upload_to='notifications/%Y/%m', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Cover')),
                ('content_id', models.BigIntegerField(blank=True, null=True, verbose_name='Content ID')),
                ('delivery_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Delivery Time')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is Sent')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Additional Data')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
