# Generated by Django 5.1.7 on 2025-03-25 10:20

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('news', 'News'), ('exam_list', 'Exam'), ('announcement', "E'lon"), ('other', 'Other')], default='other', max_length=20, verbose_name='Type')),
                ('title', models.CharField(verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Content')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=95, scale=None, size=[500, 350], upload_to='notification/%Y/%m', verbose_name='Cover')),
                ('content_id', models.BigIntegerField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Delivery Time')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification', verbose_name='Notification')),
            ],
            options={
                'verbose_name': 'User Notification',
                'verbose_name_plural': 'User Notifications',
            },
        ),
    ]
